language: php
sudo: required
dist: precise
addons:
  firefox: "47.0.1"
services:
  - docker
before_install:
  - docker pull selenium/standalone-chrome
  - docker run --net=host selenium/standalone-chrome
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
php:
  - 7.0
cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files
env:
  matrix:
      - ACCEPTANCE=true # run test

matrix:
  fast_finish: true

before_script:
  - "export DISPLAY=:99.0"
  - chmod +x ./ci/setup.sh
  - ./ci/setup.sh

script:
  - chmod +x ./ci/script.sh
  - ./ci/script.sh
