language: php
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
php:
  - 7.1.9
cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files
env:
  matrix:
      - ACCEPTANCE=true # run test

matrix:
  fast_finish: true

before_script:
  - chmod +x ./ci/setup.sh
  - ./ci/setup.sh
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - chmod +x ./ci/script.sh
  - ./ci/script.sh
