language: php
sudo: required
dist: precise
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
php:
  - 7.1.9
cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files
env:
  matrix:
      - ACCEPTANCE=true # run test

matrix:
  fast_finish: true

before_script:
  - "export DISPLAY=:99.0"
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jre
  - java -version
  - composer install

script:
  - java -jar -Dwebdriver.chrome.driver="chrome_driver/chromedriver" "selenium-server-standalone.jar"
  - vendor/bin/codecept run tests/acceptance/pl/initPLCest.php --steps
