language: php
sudo: required
dist: precise
addons:
  firefox: "46.0"
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
php:
  - 7.1.9
cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files
env:
  matrix:
      - ACCEPTANCE=true # run test

matrix:
  fast_finish: true

before_script:
  - chmod +x ./ci/setup.sh
  - ./ci/setup.sh

script:
  - chmod +x ./ci/script.sh
  - ./ci/script.sh
