DROP TABLE AUTOMATION_TEST_CASE_TW;
CREATE TABLE AUTOMATION_TEST_CASE_TW
(
       /* Data need defined to run automation testing */
       dealer_code                               NUMBER(20)    NOT NULL,
       pos_code                                  NUMBER(10)    NOT NULL,
       product_group                             NUMBER(10)    NOT NULL,
       product_scheme                            NUMBER(10)    NOT NULL,
       gender                                    VARCHAR2(1)   NOT NULL,
       national_id                               VARCHAR2(20)  NOT NULL,
       date_of_birth                             DATE          NOT NULL,
       fb_number                                 VARCHAR2(30),
       phone                                     VARCHAR2(12)  NOT NULL,
       hometown                                  VARCHAR2(100),
       brand                                     VARCHAR2(50),
       asset_make                                VARCHAR2(50),
       asset_model                               VARCHAR2(50),
       good_price                                NUMBER(18,4)  NOT NULL,
       collateral_description                    VARCHAR2(100) NOT NULL,
       downpayment                               NUMBER(18,4)  NOT NULL,
       tenor                                     NUMBER(2)     NOT NULL,
       is_fb_owner                               VARCHAR2(1)   NOT NULL,
       education                                 NUMBER(3),
       marital_status                            VARCHAR2(1)   NOT NULL,
       social_status                             NUMBER(3),
       personal_income                           NUMBER(18,4),
       family_income                             NUMBER(18,4),
       phone_reference1                          VARCHAR2(12),
       phone_reference2                          VARCHAR2(12),
       /* Data will fill after automation run */
       application_id                            VARCHAR2(20),
       case_id                                   VARCHAR2(10),
       total_score                               NUMBER(10)    NOT NULL,
       score_group                               VARCHAR2(3)   NOT NULL,
       random_number                             NUMBER(3)     NOT NULL,
       /* Scores are defined by user */
       score_user_gender_and_age                 NUMBER(3)     NOT NULL,
       score_user_reject_apps                    NUMBER(3)     NOT NULL,
       score_user_marital_status                 NUMBER(3)     NOT NULL,
       score_user_dpd_ever                       NUMBER(3)     NOT NULL,
       score_user_tenor                          NUMBER(3)     NOT NULL,
       score_user_pos_performance                NUMBER(3)     NOT NULL,
       score_user_pos_address                    NUMBER(3)     NOT NULL,
       score_user_permanent_address              NUMBER(3)     NOT NULL,
       score_user_education_work                 NUMBER(3)     NOT NULL,
       score_user_down_payment_rate              NUMBER(3)     NOT NULL,
       score_user_fb_owner_gender                NUMBER(3)     NOT NULL,
       score_user_customerage                    NUMBER(3)     NOT NULL,
       /* Scores will fill after automation run by robot */
       score_robot_gender_and_age                NUMBER(3),
       score_robot_reject_apps                   NUMBER(3),
       score_robot_marital_status                NUMBER(3),
       score_robot_dpd_ever                      NUMBER(3),
       score_robot_tenor                         NUMBER(3),
       score_robot_pos_performance               NUMBER(3),
       score_robot_pos_address                   NUMBER(3),
       score_robot_permanent_address             NUMBER(3),
       score_robot_education_work                NUMBER(3),
       score_robot_down_payment_rate             NUMBER(3),
       score_robot_fb_owner_gender               NUMBER(3),
       score_robot_customerage                   NUMBER(3),
       robot_total_score                         NUMBER(3),
       robot_score_group                         VARCHAR2(3),
       robot_random_number                       NUMBER(3),
       /* Checking score */
       score_check_gender_and_age                VARCHAR2(2),
       score_check_reject_apps                   VARCHAR2(2),
       score_check_marital_status                VARCHAR2(2),
       score_check_dpd_ever                      VARCHAR2(2),
       score_check_tenor                         VARCHAR2(2),
       score_check_pos_performance               VARCHAR2(2),
       score_check_pos_address                   VARCHAR2(2),
       score_check_permanent_address             VARCHAR2(2),
       score_check_education_work                VARCHAR2(2),
       score_check_down_payment_rate             VARCHAR2(2),
       score_check_fb_owner_gender               VARCHAR2(2),
       score_check_customerage                   VARCHAR2(2),
       check_total_score                         VARCHAR2(2),
       check_score_group                         VARCHAR2(2),
       check_random_number                       VARCHAR2(2),
       /* Checking status */
       status                                    NUMBER(1)     DEFAULT 0
);

INSERT ALL 
INTO AUTOMATION_TEST_CASE_TW
(
       dealer_code,
       pos_code,
       product_group,
       product_scheme,
       gender,
       national_id,
       date_of_birth,
       fb_number,
       phone,
       hometown,
       brand,
       asset_make,
       asset_model,
       good_price,
       collateral_description,
       downpayment,
       tenor,
       is_fb_owner,
       education,
       marital_status,
       social_status,
       personal_income,
       family_income,
       phone_reference1,
       phone_reference2,
       total_score,
       score_group,
       random_number,
       score_user_gender_and_age,
       score_user_reject_apps,
       score_user_marital_status,
       score_user_dpd_ever,
       score_user_tenor,
       score_user_pos_performance,
       score_user_pos_address,
       score_user_permanent_address,
       score_user_education_work,
       score_user_down_payment_rate,
       score_user_fb_owner_gender,
       score_user_customerage
)
VALUES
(
       95100000008,
       151012,
       250,
       910,
       'F',
       201711240956,
       TO_DATE('11/11/1994', 'DD/MM/YYYY'),
       'FB#201711240956',
       '0911140321',
       'Hồ Chí Minh',
       'HONDA',
       'HONDA',
       'VISION',
       36000000,
       'HONDA VISION',
       10800000,
       12,
       'Y',
       76,
       'O',
       8,
       35000000,
       45000000,
       '0911230912',
       '0911230913',
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0
)
INTO AUTOMATION_TEST_CASE_TW
(
       dealer_code,
       pos_code,
       product_group,
       product_scheme,
       gender,
       national_id,
       date_of_birth,
       fb_number,
       phone,
       hometown,
       brand,
       asset_make,
       asset_model,
       good_price,
       collateral_description,
       downpayment,
       tenor,
       is_fb_owner,
       education,
       marital_status,
       social_status,
       personal_income,
       family_income,
       phone_reference1,
       phone_reference2,
       total_score,
       score_group,
       random_number,
       score_user_gender_and_age,
       score_user_reject_apps,
       score_user_marital_status,
       score_user_dpd_ever,
       score_user_tenor,
       score_user_pos_performance,
       score_user_pos_address,
       score_user_permanent_address,
       score_user_education_work,
       score_user_down_payment_rate,
       score_user_fb_owner_gender,
       score_user_customerage
)
VALUES
(
       95100000008,
       151012,
       250,
       910,
       'F',
       201711240956,
       TO_DATE('11/11/1994', 'DD/MM/YYYY'),
       'FB#201711240956',
       '0911140321',
       'Hồ Chí Minh',
       'YAMAHA',
       'YAMAHA',
       'NOUVO',
       36000000,
       'YAMAHA NOUVO',
       10800000,
       12,
       'Y',
       76,
       'O',
       8,
       35000000,
       45000000,
       '0911230912',
       '0911230913',
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0
)
SELECT 1 
FROM DUAL;

SELECT * 
FROM AUTOMATION_TEST_CASE_TW
FOR UPDATE;

