DROP TABLE AUTOMATION_TEST_CASE_PL;
CREATE TABLE AUTOMATION_TEST_CASE_PL
(
       /* Data need defined to run automation testing */
       product_group                             VARCHAR2(50)  NOT NULL,
       product_scheme                            VARCHAR2(50)  NOT NULL,
       dsa_code                                  VARCHAR2(50)  NOT NULL,
       gender                                    VARCHAR2(1)   NOT NULL,
       national_id                               VARCHAR2(20)  NOT NULL,
       date_of_birth                             DATE          NOT NULL,
       fb_number                                 VARCHAR2(30),
       phone                                     VARCHAR2(12)  NOT NULL,
       hometown                                  VARCHAR2(100),
       disbursement_channel                      VARCHAR2(30),
       requested_amount                          NUMBER(18,4)  NOT NULL,
       tenor                                     NUMBER(2)     NOT NULL,
       loan_purpose                              VARCHAR2(30),
       is_fb_owner                               VARCHAR2(1)   NOT NULL,
       education                                 NUMBER(3),
       marital_status                            VARCHAR2(1)   NOT NULL,
       social_status                             NUMBER(3),
       personal_income                           NUMBER(18,4),
       family_income                             NUMBER(18,4),
       phone_reference1                          VARCHAR2(12),
       phone_reference2                          VARCHAR2(12),
       /* Data will fill after automation run */
       application_id                            VARCHAR2(20),
       case_id                                   VARCHAR2(10),
       total_score                               NUMBER(10)    NOT NULL,
       score_group                               VARCHAR2(3)   NOT NULL,
       product_score_group                       VARCHAR2(4)   NOT NULL,
       random_number                             NUMBER(3)     NOT NULL,
       /* Scores are defined by user */
       score_user_gender                         NUMBER(3)     NOT NULL,
       score_user_work_experience                NUMBER(3)     NOT NULL,
       score_user_age                            NUMBER(3)     NOT NULL,
       score_user_interest_rate                  NUMBER(3)     NOT NULL,
       score_user_dist_office_add                NUMBER(3)     NOT NULL,
       score_user_province                       NUMBER(3)     NOT NULL,
       score_user_disburse_date                  NUMBER(3)     NOT NULL,
       score_user_dpd_no_disb_apps               NUMBER(3)     NOT NULL,
       score_user_rejection                      NUMBER(3)     NOT NULL,
       /* Scores will fill after automation run by robot */
       score_robot_gender                        NUMBER(3),
       score_robot_work_experience               NUMBER(3),
       score_robot_age                           NUMBER(3),
       score_robot_interest_rate                 NUMBER(3),
       score_robot_dist_office_add               NUMBER(3),
       score_robot_province                      NUMBER(3),
       score_robot_disburse_date                 NUMBER(3),
       score_robot_dpd_no_disb_apps              NUMBER(3),
       score_robot_rejection                     NUMBER(3),
       robot_total_score                         NUMBER(3),
       robot_score_group                         VARCHAR2(3),
       robot_product_score_group                 VARCHAR2(4),
       robot_random_number                       NUMBER(3),
       /* Checking score */
       score_check_gender                        VARCHAR2(2),
       score_check_work_experience               VARCHAR2(2),
       score_check_age                           VARCHAR2(2),
       score_check_interest_rate                 VARCHAR2(2),
       score_check_dist_office_add               VARCHAR2(2),
       score_check_province                      VARCHAR2(2),
       score_check_disburse_date                 VARCHAR2(2),
       score_check_dpd_no_disb_apps              VARCHAR2(2),
       score_check_rejection                     VARCHAR2(2),
       check_total_score                         VARCHAR2(2),
       check_score_group                         VARCHAR2(2),
       check_product_score_group                 VARCHAR2(2),
       check_random_number                       VARCHAR2(2),
       /* Checking status */
       status                                    NUMBER(1)     DEFAULT 0
);

INSERT ALL 
INTO AUTOMATION_TEST_CASE_PL
(
       product_group,
       product_scheme,
       dsa_code,
       gender,
       national_id,
       date_of_birth,
       fb_number,
       phone,
       hometown,
       disbursement_channel,
       requested_amount,
       tenor,
       loan_purpose,
       is_fb_owner,
       education,
       marital_status,
       social_status,
       personal_income,
       family_income,
       phone_reference1,
       phone_reference2,
       total_score,
       score_group,
       product_score_group,
       random_number,
       score_user_gender,
       score_user_work_experience,
       score_user_age,
       score_user_interest_rate,
       score_user_dist_office_add,
       score_user_province,
       score_user_disburse_date,
       score_user_dpd_no_disb_apps,
       score_user_rejection
)
VALUES
(
       'NEW TO BANK',
       'UP CAT C - 306',
       'BAD00001',
       'F',
       201712081057,
       TO_DATE('11/11/1994', 'DD/MM/YYYY'),
       'FB#201712081057',
       '0912081057',
       'Hồ Chí Minh',
       'VNPOST',
       19000000,
       7,
       'Other',
       'Y',
       76,
       'O',
       8,
       35000000,
       45000000,
       '0912081058',
       '0912081059',
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0
)
INTO AUTOMATION_TEST_CASE_PL
(
       product_group,
       product_scheme,
       dsa_code,
       gender,
       national_id,
       date_of_birth,
       fb_number,
       phone,
       hometown,
       disbursement_channel,
       requested_amount,
       tenor,
       loan_purpose,
       is_fb_owner,
       education,
       marital_status,
       social_status,
       personal_income,
       family_income,
       phone_reference1,
       phone_reference2,
       total_score,
       score_group,
       product_score_group,
       random_number,
       score_user_gender,
       score_user_work_experience,
       score_user_age,
       score_user_interest_rate,
       score_user_dist_office_add,
       score_user_province,
       score_user_disburse_date,
       score_user_dpd_no_disb_apps,
       score_user_rejection
)
VALUES
(
       'NEW TO BANK',
       'UP CAT C - 306',
       'BAD00002',
       'M',
       201712081100,
       TO_DATE('11/11/1994', 'DD/MM/YYYY'),
       'FB#201712081100',
       '0912081100',
       'Hồ Chí Minh',
       'VNPOST',
       20000000,
       6,
       'Other',
       'N',
       76,
       'M',
       8,
       35000000,
       45000000,
       '0912081101',
       '0912081102',
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0
)
SELECT 1 
FROM DUAL;

SELECT * 
FROM AUTOMATION_TEST_CASE_PL
FOR UPDATE;

