DROP TABLE AUTOMATION_TEST_CASE_CDL;
CREATE TABLE AUTOMATION_TEST_CASE_CDL
(
       /* Data need defined to run automation testing */
       dealer_code                    NUMBER(20)    NOT NULL,
       pos_code                       NUMBER(10)    NOT NULL,
       product_group                  NUMBER(10)    NOT NULL,
       product_scheme                 NUMBER(10)    NOT NULL,
       gender                         VARCHAR2(1)   NOT NULL,
       national_id                    VARCHAR2(20)  NOT NULL,
       date_of_birth                  DATE          NOT NULL,
       fb_number                      VARCHAR2(30),
       phone                          VARCHAR2(12)  NOT NULL,
       hometown                       VARCHAR2(100),
       good_type                      VARCHAR2(50),
       brand                          VARCHAR2(50),
       asset_make                     VARCHAR2(50),
       asset_model                    VARCHAR2(50),
       good_price                     NUMBER(18,4)  NOT NULL,
       collateral_description         VARCHAR2(100) NOT NULL,
       downpayment                    NUMBER(18,4)  NOT NULL,
       tenor                          NUMBER(2)     NOT NULL,
       is_fb_owner                    VARCHAR2(1)   NOT NULL,
       education                      NUMBER(3),
       marital_status                 VARCHAR2(1)   NOT NULL,
       social_status                  NUMBER(3),
       personal_income                NUMBER(18,4),
       family_income                  NUMBER(18,4),
       phone_reference1               VARCHAR2(12),
       phone_reference2               VARCHAR2(12),
       /* Data will fill after automation run */
       application_id                 VARCHAR2(20),
       case_id                        VARCHAR2(10),
       total_score                    NUMBER(10)    NOT NULL,
       score_group                    VARCHAR2(3)   NOT NULL,
       random_number                  NUMBER(3)     NOT NULL,
       /* Scores are defined by user */
       score_user_gender_and_age      NUMBER(3)     NOT NULL,
       score_user_marital_status      NUMBER(3)     NOT NULL,
       score_user_installment         NUMBER(3)     NOT NULL,
       score_user_pos_region          NUMBER(3)     NOT NULL,
       score_user_cc_performance      NUMBER(3)     NOT NULL,
       score_user_fb_owner            NUMBER(3)     NOT NULL,
       score_user_down_payment_ratio  NUMBER(3)     NOT NULL,
       score_user_pos_performance     NUMBER(3)     NOT NULL,
       score_user_owner_dpd_ever      NUMBER(3)     NOT NULL,
       score_user_ref_dpd             NUMBER(3)     NOT NULL,
       score_user_owner_rejected      NUMBER(3)     NOT NULL,
       score_user_owner_disbursed     NUMBER(3)     NOT NULL,
       score_user_asset_brand         NUMBER(3)     NOT NULL,
       score_user_effective_rate      NUMBER(3)     NOT NULL,
       score_user_document_required   NUMBER(3)     NOT NULL,
       /* Scores will fill after automation run by robot */
       score_robot_gender_and_age     NUMBER(3),
       score_robot_marital_status     NUMBER(3),
       score_robot_installment        NUMBER(3),
       score_robot_pos_region         NUMBER(3),
       score_robot_cc_performance     NUMBER(3),
       score_robot_fb_owner           NUMBER(3),
       score_robot_down_payment_ratio NUMBER(3),
       score_robot_pos_performance    NUMBER(3),
       score_robot_owner_dpd_ever     NUMBER(3),
       score_robot_ref_dpd            NUMBER(3),
       score_robot_owner_rejected     NUMBER(3),
       score_robot_owner_disbursed    NUMBER(3),
       score_robot_asset_brand        NUMBER(3),
       score_robot_effective_rate     NUMBER(3),
       score_robot_document_required  NUMBER(3),
       robot_total_score              NUMBER(10),
       robot_score_group              VARCHAR2(3),
       robot_random_number            NUMBER(3),
       /* Checking score */
       score_check_gender_and_age     VARCHAR2(2),
       score_check_marital_status     VARCHAR2(2),
       score_check_installment        VARCHAR2(2),
       score_check_pos_region         VARCHAR2(2),
       score_check_cc_performance     VARCHAR2(2),
       score_check_fb_owner           VARCHAR2(2),
       score_check_down_payment_ratio VARCHAR2(2),
       score_check_pos_performance    VARCHAR2(2),
       score_check_owner_dpd_ever     VARCHAR2(2),
       score_check_ref_dpd            VARCHAR2(2),
       score_check_owner_rejected     VARCHAR2(2),
       score_check_owner_disbursed    VARCHAR2(2),
       score_check_asset_brand        VARCHAR2(2),
       score_check_effective_rate     VARCHAR2(2),
       score_check_document_required  VARCHAR2(2),
       check_total_score              VARCHAR2(2),
       check_score_group              VARCHAR2(2),
       check_random_number            VARCHAR2(2),
       /* Checking status */
       status                         NUMBER(1)     DEFAULT 0
);

INSERT ALL 
INTO AUTOMATION_TEST_CASE_CDL
(
       dealer_code,
       pos_code,
       product_group,
       product_scheme,
       gender,
       national_id,
       date_of_birth,
       fb_number,
       phone,
       hometown,
       good_type,
       brand,
       asset_make,
       asset_model,
       good_price,
       collateral_description,
       downpayment,
       tenor,
       is_fb_owner,
       education,
       marital_status,
       social_status,
       personal_income,
       family_income,
       phone_reference1,
       phone_reference2,
       score_user_gender_and_age,
       score_user_marital_status,
       score_user_installment,
       score_user_pos_region,
       score_user_cc_performance,
       score_user_fb_owner,
       score_user_down_payment_ratio,
       score_user_pos_performance,
       score_user_owner_dpd_ever,
       score_user_ref_dpd,
       score_user_owner_rejected,
       score_user_owner_disbursed,
       score_user_asset_brand,
       score_user_effective_rate,
       score_user_document_required
)
VALUES
(
       80000000250,
       600725,
       255,
       1019,
       'M',
       201711241007,
       TO_DATE('11/11/1995', 'DD/MM/YYYY'),
       'FB#201711240955',
       '0911140301',
       'Hồ Chí Minh',
       'DESKTOP',
       'DELL',
       'DELL',
       'DELL',
       20000000,
       'DESKTOP DELL',
       5000000,
       8,
       'N',
       76,
       'M',
       8,
       35000000,
       45000000,
       '0911230909',
       '0911140310',
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0
)
INTO AUTOMATION_TEST_CASE_CDL
(
       dealer_code,
       pos_code,
       product_group,
       product_scheme,
       gender,
       national_id,
       date_of_birth,
       fb_number,
       phone,
       hometown,
       good_type,
       brand,
       asset_make,
       asset_model,
       good_price,
       collateral_description,
       downpayment,
       tenor,
       is_fb_owner,
       education,
       marital_status,
       social_status,
       personal_income,
       family_income,
       phone_reference1,
       phone_reference2,
       score_user_gender_and_age,
       score_user_marital_status,
       score_user_installment,
       score_user_pos_region,
       score_user_cc_performance,
       score_user_fb_owner,
       score_user_down_payment_ratio,
       score_user_pos_performance,
       score_user_owner_dpd_ever,
       score_user_ref_dpd,
       score_user_owner_rejected,
       score_user_owner_disbursed,
       score_user_asset_brand,
       score_user_effective_rate,
       score_user_document_required
)
VALUES
(
       80000000250,
       600725,
       255,
       1019,
       'F',
       201711240956,
       TO_DATE('11/11/1994', 'DD/MM/YYYY'),
       'FB#201711240956',
       '0911140321',
       'Hồ Chí Minh',
       'MOBILE',
       'ASUS',
       'ASUS',
       'ASUS',
       20000000,
       'MOBILE ASUS',
       5000000,
       8,
       'Y',
       76,
       'O',
       8,
       35000000,
       45000000,
       '0911230912',
       '0911230913',
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0
)
SELECT 1 
FROM DUAL;

SELECT * 
FROM AUTOMATION_TEST_CASE_CDL
FOR UPDATE;

